#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
EcoGPT - Filter Self-QA data by answer-source consistency.

When Self-QA is generated by a smaller model (e.g. 14B), hallucination rate
is higher. This script filters out QA pairs where the answer has low overlap
with the source paragraph, indicating likely hallucination.

Usage:
    python filter_self_qa.py \
        --input data/sft/processed/self_qa.jsonl \
        --output data/sft/processed/self_qa_filtered.jsonl \
        --min_overlap 0.3 \
        --min_answer_len 30
"""

import argparse
import json
import os
import re
from collections import Counter

from loguru import logger


def char_ngrams(text: str, n: int = 3) -> list:
    text = re.sub(r'\s+', '', text)
    if len(text) <= n:
        return [text] if text else []
    return [text[i:i + n] for i in range(len(text) - n + 1)]


def ngram_overlap(text_a: str, text_b: str, n: int = 3) -> float:
    """
    Compute character n-gram overlap ratio between two texts.
    Returns: ratio of shared n-grams to total n-grams in text_a.
    """
    grams_a = Counter(char_ngrams(text_a, n))
    grams_b = Counter(char_ngrams(text_b, n))

    if not grams_a:
        return 0.0

    shared = sum((grams_a & grams_b).values())
    total = sum(grams_a.values())
    return shared / total


def extract_source_and_qa(item: dict):
    """
    Extract source paragraph, question, and answer from Self-QA output.
    Self-QA format: conversations with optional _source_paragraph metadata.
    """
    convs = item.get("conversations", [])
    if len(convs) < 2:
        return None, None, None

    question = next((m["value"] for m in convs if m.get("from") == "human"), "")
    answer = next((m["value"] for m in convs if m.get("from") == "gpt"), "")
    source = item.get("_source_paragraph", "")

    return source, question, answer


def main():
    ap = argparse.ArgumentParser(description="Filter Self-QA by answer-source consistency")
    ap.add_argument("--input", required=True, help="Input Self-QA jsonl")
    ap.add_argument("--output", required=True, help="Output filtered jsonl")
    ap.add_argument("--min_overlap", type=float, default=0.3,
                    help="Min n-gram overlap ratio between answer and source (0-1). "
                         "Lower = more lenient. 0.3 recommended for 14B.")
    ap.add_argument("--min_answer_len", type=int, default=30,
                    help="Min answer character length")
    ap.add_argument("--min_question_len", type=int, default=10,
                    help="Min question character length")
    ap.add_argument("--max_answer_len", type=int, default=2000,
                    help="Max answer length (filter verbose garbage)")
    ap.add_argument("--ngram_size", type=int, default=3)
    ap.add_argument("--filter_empty_patterns", action="store_true", default=True,
                    help="Filter answers with generic filler phrases")
    args = ap.parse_args()

    os.makedirs(os.path.dirname(args.output), exist_ok=True)

    # Generic filler patterns that indicate low-quality answers
    FILLER_PATTERNS = [
        "根据提供的信息无法", "无法确定", "没有足够的信息",
        "请提供更多", "无法回答", "不在文中提及",
        "作为AI", "作为一个AI", "我无法",
    ]

    total = 0
    kept = 0
    dropped_overlap = 0
    dropped_length = 0
    dropped_filler = 0
    overlap_scores = []

    with open(args.input, "r", encoding="utf-8") as fin, \
         open(args.output, "w", encoding="utf-8") as fout:

        for line in fin:
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
            except json.JSONDecodeError:
                continue

            total += 1
            source, question, answer = extract_source_and_qa(item)

            if not question or not answer:
                dropped_length += 1
                continue

            # Length filter
            if len(question) < args.min_question_len or \
               len(answer) < args.min_answer_len or \
               len(answer) > args.max_answer_len:
                dropped_length += 1
                continue

            # Filler pattern filter
            if args.filter_empty_patterns:
                if any(p in answer for p in FILLER_PATTERNS):
                    dropped_filler += 1
                    continue

            # Source-answer overlap filter (only if source is available)
            if source:
                overlap = ngram_overlap(answer, source, args.ngram_size)
                overlap_scores.append(overlap)
                if overlap < args.min_overlap:
                    dropped_overlap += 1
                    continue

            # Remove internal metadata before output
            out_item = {"conversations": item["conversations"]}
            fout.write(json.dumps(out_item, ensure_ascii=False) + "\n")
            kept += 1

    print(f"\n{'=' * 50}")
    print(f"  Self-QA Filter Report")
    print(f"{'=' * 50}")
    print(f"  Total:             {total}")
    print(f"  Kept:              {kept} ({kept / max(total, 1):.1%})")
    print(f"  Dropped (length):  {dropped_length}")
    print(f"  Dropped (filler):  {dropped_filler}")
    print(f"  Dropped (overlap): {dropped_overlap}")

    if overlap_scores:
        overlap_scores.sort()
        n = len(overlap_scores)
        print(f"\n  Overlap score distribution (of checked samples):")
        print(f"    min:  {overlap_scores[0]:.3f}")
        print(f"    p25:  {overlap_scores[n // 4]:.3f}")
        print(f"    p50:  {overlap_scores[n // 2]:.3f}")
        print(f"    p75:  {overlap_scores[3 * n // 4]:.3f}")
        print(f"    max:  {overlap_scores[-1]:.3f}")

    print(f"\n  Output: {args.output}")


if __name__ == "__main__":
    main()
